const { computeContribution } = require('./causalGraph')
const { pool } = require('./db')

// In-memory clientId → user mapping per document session
// Built from socket connection events
const clientIdRegistry = new Map()  // docId → Map<clientId, { userId, name, color }>

function registerClientId(docId, clientId, user) {
  if (!clientIdRegistry.has(docId)) {
    clientIdRegistry.set(docId, new Map())
  }
  clientIdRegistry.get(docId).set(clientId, user)
}

function getClientIdResolver(docId) {
  const registry = clientIdRegistry.get(docId) || new Map()
  return (clientId) => registry.get(clientId) || null
}

async function getContributionForRange(ydoc, docId, fromIndex, toIndex) {
  const resolver = getClientIdResolver(docId)
  const contributions = computeContribution(ydoc, fromIndex, toIndex, resolver)

  // For any unresolved clientIds, try to look up from Postgres
  // (covers users who contributed in a past session)
  const unresolved = contributions.filter(c => !c.author.name || c.author.name.startsWith('User '))

  if (unresolved.length > 0) {
    // clientId in Yjs is a random uint32 generated by Y.Doc()
    // We store it in a session_clients table
    // For unresolved ones, fallback to "Past Contributor"
    for (const contrib of unresolved) {
      contrib.author.name = `Past Contributor`
    }
  }

  return contributions
}

module.exports = { registerClientId, getClientIdResolver, getContributionForRange }
